# Generated by Django 5.0.6 on 2024-06-28 10:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.CharField(max_length=50, unique=True)),
                ('CourseName', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagName', models.CharField(max_length=100)),
                ('isHidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('EmpStatus', models.CharField(blank=True, default='Unknown', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddUserTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('BatchNumber', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=50)),
                ('eval_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=50)),
                ('Term', models.IntegerField()),
                ('ClassModality', models.CharField(max_length=50)),
                ('OverallProfRate', models.IntegerField()),
                ('ProfDifficulty', models.IntegerField()),
                ('RetakeProf', models.BooleanField()),
                ('BigSkyUsageRate', models.IntegerField()),
                ('ProfAttendance', models.IntegerField()),
                ('GradeReceived', models.IntegerField(blank=True, null=True)),
                ('DateAdded', models.DateTimeField(default=datetime.datetime.now)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvalSys.coursetb')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvalSys.teachertb')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation_TagTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EvaluationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvalSys.evaluationtb')),
                ('TagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvalSys.tagtb')),
            ],
        ),
        migrations.CreateModel(
            name='User_Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EvaluationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvalSys.evaluationtb')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Eval_User',
        ),
    ]
