# Generated by Django 5.0.6 on 2024-06-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0004_teacher_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Course',
            new_name='Teacher_CourseTB',
        ),
    ]
