# Generated by Django 5.0.6 on 2024-06-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0009_alter_evaluationtb_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_EvaluationTB',
        ),
    ]
