# Generated by Django 5.0.6 on 2024-07-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0011_teacher_bookmarktb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_bookmarktb',
            name='UserID',
        ),
    ]
