# Generated by Django 5.0.6 on 2024-07-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0012_remove_teacher_bookmarktb_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_bookmarktb',
            name='TeacherID',
        ),
    ]
