# Generated by Django 5.0.6 on 2024-07-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0013_remove_teacher_bookmarktb_teacherid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_BookMarkTB',
        ),
    ]
