# Generated by Django 5.0.6 on 2024-07-07 06:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0014_delete_teacher_bookmarktb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_BookmarkTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateTimeField(default=datetime.datetime.now)),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvalSys.teachertb')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('TeacherID', 'UserID')},
            },
        ),
    ]
