# Generated by Django 5.0.6 on 2024-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0016_alter_evaluationtb_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationtb',
            name='BigSkyUsageRate',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='evaluationtb',
            name='GradeReceived',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationtb',
            name='OverallProfRate',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='evaluationtb',
            name='ProfAttendance',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='evaluationtb',
            name='ProfDifficulty',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
