# Generated by Django 5.0.6 on 2024-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0019_alter_evaluationtb_bigskyusagerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusertb',
            name='BatchNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addusertb',
            name='Department',
            field=models.CharField(default=122, max_length=100),
            preserve_default=False,
        ),
    ]
