# Generated by Django 5.0.6 on 2024-07-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalSys', '0020_alter_addusertb_batchnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusertb',
            name='BatchNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addusertb',
            name='Department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
